name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #login to docker
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #build the dev version of the client and run tests
      - run: docker build -t rtpa25/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rtpa25/react-test npm test
 
      #build the prod versions of all the projects
      - run: docker build -t rtpa25/multi-client-25 ./client
      - run: docker build -t rtpa25/multi-nginx-25 ./nginx
      - run: docker build -t rtpa25/multi-server-25 ./server
      - run: docker build -t rtpa25/multi-worker-25 ./worker
 
      #push all the build images to dockerhub
      - run: docker push rtpa25/multi-client-25
      - run: docker push rtpa25/multi-nginx-25
      - run: docker push rtpa25/multi-server-25
      - run: docker push rtpa25/multi-worker-25
 
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-gh
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip